- [gotrick](https://github.com/faisalaffan/gotrick) — Golang tips and trick for future development
- [belajardart](https://github.com/faisalaffan/belajardart) — Dasar-dasar pemrograman Dart & Best Practice Flutter
